--- !ditz.rubyforge.org,2008-03-06/project 
name: IFM
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: maps
- !ditz.rubyforge.org,2008-03-06/component 
  name: items
- !ditz.rubyforge.org,2008-03-06/component 
  name: tasks
- !ditz.rubyforge.org,2008-03-06/component 
  name: prog
- !ditz.rubyforge.org,2008-03-06/component 
  name: output
- !ditz.rubyforge.org,2008-03-06/component 
  name: lang
releases: []

